export const REQUEST_UNIVERSITIES = 'REQUEST_UNIVERSITIES';
export const RECEIVE_UNIVERSITIES = 'RECEIVE_UNIVERSITIES';
export const POP_UNIVERSITY = 'POP_UNIVERSITY';
export const ACCEPT_UNIVERSITY = 'ACCEPT_UNIVERSITY';
export const REJECT_UNIVERSITY = 'REJECT_UNIVERSITY';
export const VIEW_UNIVERSITY = 'VIEW_UNIVERSITY';
export const TOGGLE_SEE_ALL = 'TOGGLE_SEE_ALL';
export const CLEANUP_RECENT_STATE = 'CLEANUP_RECENT_STATE';
