export const REQUEST_UNIVERSITIES = 'REQUEST_UNIVERSITIES';
export const RECEIVE_UNIVERSITIES = 'RECEIVE_UNIVERSITIES';
export const POP_UNIVERSITY = 'POP_UNIVERSITY';
export const PICK_UNIVERSITY = 'PICK_UNIVERSITY';
export const REJECT_UNIVERSITY = 'REJECT_UNIVERSITY';
